import {
  ExecuteRCLostAction,
  ExitOnRCLost,
  FinishAction,
  FlyToWaypointType
} from './global'
import { PointType } from './point'

/**
 * @description
 * - [`waylines.wpml`](https://developer.dji.com/doc/cloud-api-tutorial/en/api-reference/dji-wpml/waylines-wpml.html) is a file directly executed by the aircraft, defining specific drone flight and payload action commands. These commands are generated by DJI Pilot 2, DJI Flighthub 2 or other software, and can also be directly edited and developed by developers. The `waylines.wpml` file consists of two parts:
 * 1. Mission information: Mainly contains `wpml:missionConfig` element, defining global parameters for wayline missions.
 * 2. Wayline information: Mainly contains `Folder` element, defining detailed wayline information (path definition, action definition, etc.). Each `Folder` represents an executable wayline. Specifically, when using "oblique photography" template, 5 executable waylines will be generated, corresponding to 5 `Folder` elements in `waylines.wpml`.
 */
export interface WaylineFile {
  Folder: {
    /**
     * Waypoint information (including waypoint longitude, latitude and height, etc.)
     */
    Placemark: Array<PointType>
    /**
     * Global wayline flight speed
     * - m/s
     * - [1,15]
     * - Note: This element defines the target flight speed of the aircraft in the entire wayline generated by this template. If this element is additionally defined for a waypoint, the local definition will override the global definition.
     */
    autoFlightSpeed: string
    /**
     * Execution height mode
     * - `WGS84`: Ellipsoid height mode
     * - `relativeToStartPoint`: Relative to takeoff point height mode
     * - `realTimeFollowSurface`: Use real-time terrain following mode, only supports M3E/M3T/M3M, M3D/M3TD
     * - Note: This element is only used in `waylines.wpml`.
     */
    executeHeightMode: 'WGS84' | `relativeToStartPoint` | `realTimeFollowSurface`
    /**
     * Template ID
     * - Note: This ID must be unique within a kmz file. It is recommended to start from 0 and increment monotonically. In template.kml and waylines.wpml files, this id will be used to associate the template with the generated executable wayline.
     */
    templateId: string
    /**
     * Wayline ID
     * - Note: This ID must be unique within a wayline. It is recommended to start from 0 and increment monotonically.
     */
    waylineId: string
  }
  /**
   * Mission information
   */
  missionConfig: {
    /**
     * Aircraft model information
     */
    droneInfo: {
      droneEnumValue: '67'
      droneSubEnumValue: '1'
    }
    /**
     * Lost control action type
     */
    executeRCLostAction: ExecuteRCLostAction
    /**
     * Whether to continue wayline execution when lost control
     */
    exitOnRCLost: ExitOnRCLost
    /**
     * Wayline end action
     */
    finishAction: FinishAction
    /**
     * Fly to first waypoint mode
     */
    flyToWaylineMode: FlyToWaypointType
    /**
     * Global return home height
     * - m
     * - Note: When aircraft returns home, it first climbs to this height, then returns home.
     */
    globalRTHHeight: string
    /**
     * Global wayline transition speed
     * - m/s
     * - [1,15]
     * - Note: Speed of aircraft flying to the first waypoint of each wayline. Speed of aircraft recovering from current position to breakpoint when wayline mission is interrupted.
     */
    globalTransitionalSpeed: string
    /**
     * Payload model information
     */
    payloadInfo: {
      payloadEnumValue: '53'
      payloadPositionIndex: '0'
      payloadSubEnumValue: '2'
    }
    /**
     * Safe takeoff height
     * - m
     * - [2, 1500] (Height mode: relative to takeoff point height)
     * - Note: After aircraft takes off, it first climbs to this height, then flies to first waypoint according to "fly to first waypoint mode" settings. This element only takes effect when aircraft has not taken off.
     */
    takeOffSecurityHeight: string
  }
}
